### PR TITLE
apothecary more compatible with other fluid containers

### PR DESCRIPTION
**Pull request by cech12**
let apothecary be more compatible with other fluid containers
- filling apothecary with lava works like filling with water
- emptying apothecary with fluid containers also possible now

Edit: Can be tested with mods like [Ceramic Bucket](https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket) or [Big Buckets](https://www.curseforge.com/minecraft/mc-mods/bigbuckets).

### CODE REVIEW

**Comment by cech12** [comment]
Question related to these lines of code:
Why is the possibility to get the fluids out of the apothecary deactivated when Garden Of Glass mod is loaded?

**Comment by Alwinfy** [comment]
yeah, infinite water's supposed to be gated behind Rod of the Seas

**Comment by cech12** [comment]
Ah okay! :)

**Comment by cech12** [comment]
But this PR don't change anything of the behaviour when Garden Of Glass is loaded. :D

**Pull request merged**
