### PR TITLE
[1.16] Assorted low-hanging-fruit backports

### PR DESCRIPTION
**Pull request by quat1024**
* Jappa texture cacophonium block https://github.com/VazkiiMods/Botania/commit/a90fdba64d505ba489aa7922585a72756a5c53d1
  * I couldn't get datagen working at all (running `runData` just crashed immediately) so i commented out the code that generated the model and moved the model to the manual-models directory. Oh well.
* Pressing F1 hides tater names https://github.com/VazkiiMods/Botania/commit/3835af698ded009fe35368441a9622dad1d72ae0
  * `renderNames` is spelled like `isGuiEnabled` in MCP
* Horn of the Canopy works on vines https://github.com/VazkiiMods/Botania/commit/4d91a5add83f09796a3dfda83c7acbebc3596b4b
* Phantom Ink can be applied to luminizers https://github.com/VazkiiMods/Botania/commit/2e013544522612bce539f4907669b4d62796d6aa
  * I don't think that that commit actually works (isNoParticle checked in the wrong spot) so I fixed it up, ~~expect a patch forward-porting it to 1.18~~ merged 26cb1d075116856fa229a739c92243258327127c

### CODE REVIEW

**Comment by williewillus** [comment]
uhh I'm gonna get to this sometime tm

**Comment by artemisSystem** [comment]
Still relevant?

**Comment by quat1024** [comment]
🤞

**Comment by williewillus** [comment]
hope this still builds

**Pull request merged**
