### PR TITLE
Botania Shader Compatibility for Particles

### PR DESCRIPTION
**Pull request by blagdorfinguy**
When a shader pack uses GLSL deferred rendering, particles with transparency are not rendered correctly. This change (reflected in comments on the config file) will change the rendering method when shaders are set to false in the config, so particles render opaquely (albeit not quite as pretty as they render as is, with shaders they would not have rendered at all, so I feel this change is beneficial but not perfect)

### CODE REVIEW

**Comment by williewillus** [comment]
I think overloading this on the existing `useShaders` option is confusing and makes the call site code confusing. Can you make a new config instead like `opaqueParticles`?

**Comment by williewillus** [comment]
Also, you didn't implement this on Fabric

**Comment by blagdorfinguy** [comment]
Unfamiliar with Fabric, but WIP

**Comment by blagdorfinguy** [comment]
Finished fabric and adjusted config. closing request and resubmitting

**Pull request closed without merging**
