### PR TITLE
Fix state leak causing hand items to render transparently

### PR DESCRIPTION
**Pull request by extclp**

### CODE REVIEW

**Comment by williewillus** [comment]
Hi, thanks for all the PR's. In the future, please make sure your commit messages are more descriptive about what the actual problems and fixes are. The PR's can be hard to review and hard to understand after the fact otherwise.

I'll adjust them for you on this set of PR's as an example to demonstrate.

**Comment by williewillus** [comment]
Also, screenshots and other proof that the fix actually fixes things would be great too.

**Comment by extclp** [comment]
When i use shader,  part  item will become translucent in main hand,  the part item include  food and more

**Comment by extclp** [comment]
Mods:
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] bedrock-miner-1.20.1-1.1.9
  [✔] Botania-1.20.1-441-FABRIC-SNAPSHOT
  [✔] continuity-3.0.0-beta.3+1.20.1
  [✔] dynamic-fps-2.4.0
  [✔] fabric-api-0.87.0+1.20.1
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] gardenofglass-1.11
  [✔] indium-1.0.24+mc1.20.1
  [✔] InventoryProfilesNext-fabric-1.20-1.10.6
  [✔] iris-mc1.20.1-1.6.7
  [✔] itemscroller-fabric-1.20.1-0.20.0
  [✔] lazydfu-0.1.3
  [✔] libIPN-fabric-1.20-3.0.2
  [✔] malilib-fabric-1.20.1-0.16.1
  [✔] Patchouli-1.20.1-82-FABRIC-SNAPSHOT
  [✔] sodium-fabric-mc1.20.1-0.5.1
  [✔] trinkets-3.7.1
  [✔] tweakeroo-fabric-1.20.1-0.17.1
  [✔] voicechat-fabric-1.20.1-2.4.20

**Pull request merged**
