### PR TITLE
Fixed phantom mana bursts triggering the same block multiple times.

### PR DESCRIPTION
**Pull request by tiggerbiggo**
Fixes https://github.com/Vazkii/Botania/issues/3121

### CODE REVIEW

**Comment by tiggerbiggo** [comment]
Ignore the force push, that was to fix a mistaken commit to this PR and move it to another branch.

**Comment by williewillus** [comment]
remove the comment since the code is self-explanatory enough. otherwise looks good.

**Comment by williewillus** [comment]
one more thing: does this need to be saved? I'm thinking it should be

**Comment by Alwinfy** [comment]
At this point, why don't we just have a helper function for serializing/deserializing a position to NBT (heaven knows enough things use it)

**Pull request closed without merging**
