### PR TITLE
Make recipes for cracked and mossy things vanilla-consistent

### PR DESCRIPTION
**Pull request by artemisSystem**
- Changes cracked livingrock brick recipe to be smelting livingrock brick in furnace, instead of crafting it with cobblestone
- Changes recipes for mossy things to use vines or moss blocks instead of seeds
- This change is 7 years overdue (1.8) ~~except it's only 5 since that's how long ago botania 1.10 released, which was the next version after 1.7~~

### CODE REVIEW

**Comment by williewillus** [comment]
Looks good but rebase to 1.18.x please

**Comment by artemisSystem** [comment]
Will do

**Comment by artemisSystem** [comment]
Don't merge yet i forgot to actually check if it builds and puts all the datagen in the right place after merging

**Comment by artemisSystem** [comment]
Ok it seems good

**Pull request merged**
