### PR TITLE
Lexica Botania lang_en corrections

### PR DESCRIPTION
**Pull request by isochronous**
This is the continuation of PR https://github.com/Vazkii/Botania/pull/1789 - Since I managed to rebase too far back, I got git into a really weird state where it was just easier to wipe it out and reapply the changes to a new branch. A single commit for your merging pleasure.

### CODE REVIEW

**Comment by isochronous** [comment]
Arg! Didn't notice the merge commit. Please hold.

**Comment by isochronous** [comment]
Actually, I can't seem to rebase that merge commit - I did `git rebase -i origin/lex-botania-lang_en-corrections lex-botania-lang_en-corrections` and it pulled in the "corrected spelling & grammar" etc. commit and then jumped to the commit ("fixed a typo") BEFORE the merge commit. This is not my first time squashing commits, but I honestly have no idea what's going on with this. I think the situation may have gotten confused because I updated my branch with the latest from upstream/master between commits.

**Comment by yrsegal** [comment]
try squashing by commit sha1 (`git rebase -i ea10c48439082814e32f1bbc610d7ab31242bb30`)

**Comment by isochronous** [comment]
Okay, there we go - turned out the problem was git apparently does not like the way Sublime Text 3 handles file streams or something, because it would open the "interactive" text file and then git would immediately act as if I'd saved and closed the file, resulting in a completely empty commit that just made things worse. I changed my system to use notepad as the default .txt file handler and rebased again, and this time got the expected results.

**Comment by yrsegal** [comment]
you don't use vim?

**Comment by isochronous** [comment]
Nope, not that hardcore. Used to be pretty proficient with emacs back in
high school, though.

**Pull request merged**
