### PR TITLE
Generating flowers give comparator output based on mana

### PR DESCRIPTION
**Pull request by tiggerbiggo**
0 redstone signal if flower is empty of mana, 15 redstone signal when
full

### CODE REVIEW

**Comment by williewillus** [comment]
use TilePool.calculateComparatorLevel instead of redoing the math, the method handles some edge cases (like when the fraction is so small it rounds towards zero but there's mana there so the output *shouldn't* be zero).

**Comment by williewillus** [comment]
actually, since this is an api class, you might want to move that TilePool method somewhere in the API and update calls to it. Feel free to put it wherever for now, the API needs to be cleaned up anyways.

**Comment by tiggerbiggo** [comment]
Ok, I changed the method used, but given my limited knowledge of Botania's API I do not feel I am qualified to move classes around, I can't really say I feel comfortable changing more than I need to, although I could potentially just do a refactor in intellij. Should that not be in a separate change though, or do you think it should be bundled in this one?

**Comment by tiggerbiggo** [comment]
Don't approve this yet, there's a bug. It seems to update the comparator when it is generating mana, but doesn't update when it's sending that mana to a spreader. I got around this by adding a clock that pulses on the other side of the flower and gives it a block update, but i'm not sure how to solve that, since i'm new to mc modding. I'll do a bit of research but if anyone knows why this might be let me know and i'll make a change.

**Pull request closed without merging**
