### PR TITLE
Make hoes tilt the ground on certain days

### PR DESCRIPTION
**Pull request by eutro**

### CODE REVIEW

**Comment by Hubry** [comment]
but I haven't said yes
smh

**Comment by eutro** [comment]
...yet?

**Comment by Hubry** [comment]
not. yet.

**Comment by williewillus** [comment]
Why

**Comment by Alwinfy** [comment]
Less than a week left :wacko:

**Comment by Hubry** [comment]
Looks like there is no point in merging this now :tater:

**Comment by eutro** [comment]
Botania will not make it to April 2022 confirmed.

**Pull request closed without merging**
