### PR TITLE
Re translated ko_KR.lang v2

### PR DESCRIPTION
**Pull request by jomin398**
Now,I know how to update it.
Whatever,This is second translated file. 
https://github.com/jomin398/Botania/commit/a6c020b20a5962e06b051a72727d3d7457c9ea7c
###More smoother than last time. 
##I deleted last translated file by mistake:(

### CODE REVIEW

**Comment by Tamaized** [comment]
You're still trying to merge branches...

**Comment by Vazkii** [comment]
STOP

**Comment by jomin398** [comment]
Why close it?
Something is wrong?
(I don't know how to update edited file.)

2016. 11. 7. 오전 6:31에 "Vasco Lavos" <notifications@github.com>님이 작성:

**Comment by Vazkii** [comment]
Delete your repository and fork it again because you have an ancient version and all your PRs are including hundreds of commits from months ago.

**Comment by yrsegal** [comment]
I think the problem is more that they're trying to merge into 1.7.10-final

**Comment by jomin398** [comment]
So,can I re upload it to newest version?
(If 1.7.10 update is Ended??)

**Comment by Vazkii** [comment]
Ah. 1.7 is no longer supported. If you want to merge something, pull and merge from master.

**Pull request closed without merging**
