### PR TITLE
Update pt_BR.lang

### PR DESCRIPTION
**Pull request by MrKunji**
I derped baddly, pretty much it:

I need to be (A LOT) more careful from now and on :3

### CODE REVIEW

**Comment by LorenzoDCC** [comment]
Son, I am disappoint.

**Comment by TheKingBR** [comment]
Me too

**Comment by MrKunji** [comment]
Shhhh. Go back to the forum, don't make a crowd here.

**Comment by AnimadorX** [comment]
oh... eu também coloquei D:

**Pull request merged**
