### PR TITLE
Fixed some typos and rephrased some of the wording in the descriptions.

### PR DESCRIPTION
**Pull request by KamranMackey**
I have fixed some typos, and I have rephrased some of the wording in the descriptions. Please let me know @Vazkii if I need to do anything else or if I don't then just tell me that it looks fine or something. :smiley:

### CODE REVIEW

**Comment by MrKunji** [comment]
Line 158, there is 'quanity' instead 'quantity'

**Comment by Vazkii** [comment]
Does this really matter? You also changed the copyright header, which makes it in consist with the other 500+ classes.

**Comment by KamranMackey** [comment]
Yeah, it does matter, @Vazkii. I'm OCD about these things.

**Comment by Vazkii** [comment]
Then don't update the copyright header and squash all of these into one commit.

**Comment by KamranMackey** [comment]
@Vazkii How do I squash commits into just one commit?

**Comment by Vazkii** [comment]
Look into git rebase.

**Comment by KamranMackey** [comment]
Will do, except for the fact that I made these commits using GitHub's in-line editor. How am I supposed to squash commits that were made in the in-line editor?

**Comment by KamranMackey** [comment]
@Vazkii Will do, except for the fact that I made these commits using GitHub's in-line editor. How am I supposed to squash commits that were made in the in-line editor?

**Comment by KamranMackey** [comment]
And @MrKunji blame Vazkii. She's the one who made that typo. :P

**Pull request closed without merging**
