### PR TITLE
Make Mana Bursts use the correct source coordinates when fired from a Blaster. Fixes #621

### LINKED ISSUE #621: Bore Warp lens does not drop items when fired from a Mana Blaster
When a mana burst is fired from a mana blaster with a bore warp composite lens, any blocks it breaks appear to disappear into oblivion, while when fired from a redstone mana spreader, any blocks broken drops behind the spreader as an item.

### PR DESCRIPTION
**Pull request by ruifung**
Make the constructor set the burst source as the players coordinates, when its initialized with a EntityPlayer object.

### CODE REVIEW

**Comment by Vazkii** [comment]
That will break everything else.

**Comment by ruifung** [comment]
Well, you know the codebase better then me. But out of curiosity, how would it break everything else?

**Comment by Vazkii** [comment]
I don't mean literally everything else. But the -1 on Y tells the burst that it wasn't fired from a spreader which is used in a few places. Next off, you can't convert entity positions to block positions by casting to int, you need to run them through MathHelper.floor_double().

**Comment by ruifung** [comment]
Thanks for the clarification.

**Pull request closed without merging**
