### PR TITLE
Fix #1728 - Grass seeds will not spread to dirt/grass blocks under other blocks

### LINKED ISSUE #1728: Pasture seeds will spread to dirt blocks underneath other blocks
When using a seed, the initial spread will travel to dirt blocks covered by other blocks.

### PR DESCRIPTION
**Pull request by blacksmithgu**
Updates BlockSpawner in common/item/ItemGrassSeeds to not spread to dirt and grass blocks which have a non-air-like block above them. Added a good amount of comments and fixed all of the warnings and strange variable names (eg, "par1ItemStack" -> "itemStack") as well.

If neccessary, the non-functionality-critical parts can be removed.

Are there other block spawners where this change is neccessary?

### CODE REVIEW

**Comment by yrsegal** [comment]
you messed with V's item params. she won't accept this PR request, probably. Just edit the code you're working on.

**Comment by blacksmithgu** [comment]
Thought as much. This should get rid of the bulk of the extraneous changes.

**Comment by TheWhiteWolves** [comment]
I'll let Vaz decide if this should be pulled but first have you tested that it all functions without breaking anything else and works as intended?

**Comment by blacksmithgu** [comment]
As in the other PR, there isn't a big unit testing base to work on, but here are some screenshots:

Example Original Setup, with some blocks sitting on top of the dirt:


Addition of Pasture Seeds allows grass to grow under snow (as it has a light opacity of 1), but prevents it from growing under cobblestone, slabs, or stairs. Grass grows normally in the opposite direction.





The other variants also work (golden scorched, etc).

**Pull request merged**
