### PR TITLE
ManaPool#getMaxMana

### PR DESCRIPTION
**Pull request by ramidzkh**
* Make the Mana Mirror use the Mana pool's proper capacity
* Encapsulate manaCap field

### CODE REVIEW

**Comment by artemisSystem** [comment]
Hi!

Thanks for your contribution. What's the reason for this change?

**Comment by ramidzkh** [comment]
Custom mana pools that can have different mana caps. Currently I have to mixin these hooks in for my mod and not e.g. overflow the mana mirror durability bar

**Comment by artemisSystem** [comment]
Got it, that makes sense. Yeah, this would be nice to have. I'm currently in the process of making some changes to the mana API myself (see [here](https://lists.sr.ht/~williewillus/violet-moon/patches/36327), further changes pending), but i'll have a look at this PR when that's landed.

**Comment by williewillus** [comment]
Applied manually (artemis is pushing her mana changes til later, so this is fine to go in for now): 01f5f6fddb0d75f322b38e63a803efb1adde93db

**Pull request closed without merging**
