### PR TITLE
Added ja_JP.lang

### PR DESCRIPTION
**Pull request by elbo2525**
Update ja_JP.lang

### CODE REVIEW

**Comment by TheWhiteWolves** [comment]
Squash your commits down to one please

**Comment by williewillus** [comment]
Also since this is so big it'd be nice if we could have someone else knowledgeable look over it as well

**Comment by williewillus** [comment]
Oh I just looked at the lang file..

If you have not translated something, do not include it in the ja-JP lang file, it will be inherited from en_US automatically. If you copy it, then it will desync - if en_US gets updated then the copy in ja-JP will be old and potentially translated incorrectly.

Only include the lines that are actually in Japanese, leave anything out that you haven't translated.

**Comment by williewillus** [comment]
I don't think the other lang files follow this rule exactly, but no better time to start :P

**Comment by elbo2525** [comment]
OK, I got it. I'll correct the file.

**Pull request closed without merging**
