### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by Greenicefrost**
Botania r1.6-191(3rd)

### CODE REVIEW

**Comment by Mrkwtkr** [comment]
你怎么还是把名字加进去了？

**Comment by TehporP** [comment]
你好恶心诶，明明不是你做的却还强行著名，不会装逼不要装好吗

**Comment by Greenicefrost** [comment]
TehporP你这种没参与汉化的没资格说话

**Comment by TehporP** [comment]
真恶心，说的好像你有资格一样

**Comment by Greenicefrost** [comment]
加名字怎么了？你敢说所有汉化文本里没有加名字的？多管闲事

**Comment by TehporP** [comment]
我就问你一句啊。。。尽管我是汉化格雷的   但是你翻译的句子实在是逻辑混乱
当妈替换你的实在是情理之中 你咋就不能面对现实么  不好就是不好 改正了我们还是好朋友
但是硬要打肿脸充胖子我也不好说 另外 这是Github 多人合作平台  把别人劳动成果占为己有 
大丈夫？
我要考试去了
实在不屑与你这种只会固执的 无脑的拒绝别人的意见的人争论
不然我也会变成这样的人
qq 20150608172642

**Comment by ExtraMeteorP** [comment]
真是恶俗

**Comment by Greenicefrost** [comment]
啥叫当妈替换我？本来以前就是他汉化的，几十个版本没续更，玩家们都急了，我接坑怎么了？还有这关你什么事？谁跟你是朋友了？逻辑混乱？再混乱也比你GT翻译通顺

**Comment by TehporP** [comment]
好可怕 我自然知道我GT是有很多问题 但是我尊重了每个人做出的贡献 现在的文本上基本上都注明了每个参加汉化的人 哪怕尽管他只汉化了一行 我也会加上去  不像你 鸠占鹊巢（ jiū zhàn què cháo） 我也不好说啥

**Comment by Greenicefrost** [comment]
现在，嗯没错，现在，也就是说以前你就没加！所以你有资格说我？你不好说啥还在这瞎嚷嚷啥？卖弄？当妈都没说什么你一个外人在这吵什么？爱用用不用一边玩去！一开始就这种态度，鬼才给你好脸色！

**Comment by TehporP** [comment]
走之前做个评价吧
我知道这是你第一个接手的mod，是个大mod，而且你没有放弃，这是值得鼓励的
然后呢你知道如何正确的使用Github，同样也展现了你的技术水平
但是从本地化来说，你做的不怎么样
我人糙理不糙
希望你能在本地化上的的路上越走越远，别摔死了

**Comment by Mrkwtkr** [comment]
绿冰，说真的，别在里面加个人的名字，看着像小广告。你要是想让人知道你参与了付出了，我给你在搬运那边说。我不在的这段时间里，感谢你接坑，让汉化能继续更新，让大家都能玩到汉化的模组，现在我也有空了，回来在校正，表达不对的我会修正回去，就比如“催化水晶在配置文件已关闭”这个错误，坑了不少玩家，但你最近的PR把它又改回去了，还有力量中继器那边的翻译现在还是“魔力中继器”。作为本地化的，我们就要对自己的翻译负责，多注意语言的表达和通读流畅的问题吧，你还可以做得更好。

**Comment by Greenicefrost** [comment]
很抱歉，当妈你继续吧，我罢工了。看到那种人就不爽！随便你怎么想了~

**Comment by autopsychorhythmia** [comment]
....

**Comment by MyDeloreanWontStart** [comment]
wtf

**Comment by KlutzLament** [comment]
They're discussing changes to the Chinese translation in Chinese. What's wrong with that?

**Comment by MyDeloreanWontStart** [comment]
i only speak chinese, lol.

**Comment by KlutzLament** [comment]
You can read and write English well enough.

**Comment by MyDeloreanWontStart** [comment]
No, no. Sorry, I'm tired. English is my main language. I speak Chinese for business, but I can't read or write it.

**Comment by 3TUSK** [comment]
@KlutzLament @MyDeloreanWontStart Just FYI for people who are curious and wonder what was going on, @Greenicefrost wanted to update the zh_CN.lang but he added credits at the head of the whole file as well as some other place. The core problem is that he only added his credits and as y'all guys can see there are more contributors than only himself, which is definitely unacceptable. As a result @Mrkwtkr (note: in the context "当麻" refers to him, since it's part of his chinese id in some forums, so don't use google translation in case of misunderstanding), the guy who is the major contributor of Simplified Chinese localization of Botania, became disappointed indeed. Furthermore, the inaccurate translation made by Greeniceforst has caused misunderstanding among serval players (for example, one of my friend failed to summon Gaia but the chat message reminded that "he should check the Botanina config file to see if Gaia is disabled." which directly made him stop play our server. After I checked the source code and the en_US.lang I realized that he just built the worng structure, and the translation of [that message] (https://github.com/Vazkii/Botania/blob/master/src/main/resources/assets/botania/lang/en_US.lang#L67) was ambiguous).
As for @TehporP , he was just passing by here and he became mad, too. But he seems over-reacting and deny Greeniceforst's contribution (see the 3rd comment, which is his first comment), which lead to a unpleasant quarrel. TehporP claimed that Greeniceforst's translation was bad (which is not the real fact) and states that he MUST add all contributors' name and took his GregTech5 Chinese translation project as an evidence; and he also claim that Mrkwtkr should replace Greeniceforst to continue Botania translation. On the other hand Greeniceforst said zh_CN.lang of Botania has been out-of-date for more than three mouths (which can be verified by the contribution history) and it is NECESSARY to catch up ASAP, no matter who is going to do it; also he said TehporP is not qualified to interfere since he have never contribute the translation. From my perspective the quarrel can be called "drama" because it's meaningless.
At last Mrkwtkr summarize that adding one person's name into the file is like a advertisement when you browsing some website, which is not good; he also pointed out that some translation is ambiguous; last but not least, he appreciated his contribution. Greeniceforst said he quit, and he was angry about TehporP.
@ExtraMeteorP was also passing by here and he said he disgusts greeniceforst.

I have done my best to translate, and hope everyone can see it clearly. Also hope everyone have a good day and not be disappointed due to such a unhappy conversation.

**Comment by MyDeloreanWontStart** [comment]
Aha, thank you. I was a bit confused.

**Comment by 3TUSK** [comment]
Oh, sorry for my poor English.

**Comment by MyDeloreanWontStart** [comment]
Actually, I've dealt with much, much worse english. ;)

**Comment by liach** [comment]
Why everyone is worrying about localization but not contribute some code... Botania is in the lack of code, there are too much resources. Btw why all magic mods have a stupid book! That makes magic mods even more boring than those technic mods.

**Comment by Lazersmoke** [comment]
I summon @Vazkii to resolve this conflict

**Comment by 3TUSK** [comment]
@liach Differing in Thaumonomicon, Lexica Botania is more likely to become a "puzzle book" because of its lack of some usage of item (e.g. Thor Ring, Loki Ring). In addition, differing from previous two, if Blood Magic had a in-game guide book it should clearly record how to build the ritual because it is too large. Btw if Thaumonomicon is as detailed as the guidebook in RotaryCraft, Thaumcraft will be a tech mod rather than magic mod.

**Comment by 3TUSK** [comment]
@Lazersmoke Actually the conflict has been resolved... Greeniceforst said he quit at last.

**Comment by Ahrwing** [comment]
我来晚了……

**Pull request closed without merging**
