### PR TITLE
[1.19] Add cosmetic tooltip for Manaseer Monocle

### PR DESCRIPTION
**Pull request by Aegide**
The Manaseer Monocle is a cosmetic trinket, with the feature "cosmetic override".
So the keyword "Cosmetic" should be visible in the tooltip.

### CODE REVIEW

**Comment by williewillus** [comment]
Target 1.19 please.

**Review by Aegide — COMMENTED** [review]
Done

**Comment by Aegide** [comment]
> error: cannot find symbol TranslatableComponent

Fuck.

**Comment by williewillus** [comment]
Component.translatable is the replacement

**Comment by Aegide** [comment]
Done, thanks !

**Pull request merged**
