### PR TITLE
Fix fabric stridersash jump heights

### PR DESCRIPTION
**Pull request by Alwinfy**

### CODE REVIEW

**Comment by williewillus** [comment]
explain? these constants should not be different from forge.

**Comment by Alwinfy** [comment]
no idea how they're different but they work experimentally the same as forge

**Comment by williewillus** [comment]
concern

**Comment by Hubry** [comment]
Better idea: don't call this 3 times? It adds motion 3 times because the equip check uses an `instanceof`
https://github.com/Vazkii/Botania/blob/4c39b77de3e430ce90920202851fc0b39faf79c2/src/main/java/vazkii/botania/mixin/MixinLivingEntity.java#L89-L91

**Comment by Alwinfy** [comment]
Yeah okay that ought to do it :wacko:

**Pull request closed without merging**
