### PR TITLE
Added a config option for configuring the mana cost of Flugel Tiara

### PR DESCRIPTION
**Pull request by lepakko683**
Made the mana cost of Flügel Tiara configurable for balancing purposes.

### CODE REVIEW

**Comment by RX14** [comment]
This broke the build https://github.com/Vazkii/Botania/blob/007a365e39518c1ebb9a27db2bfba4f24bd6746f/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemFlightTiara.java#L246 here because `COST` no longer exists.

**Comment by lepakko683** [comment]
Would [this](https://github.com/lepakko683/Botania/commit/064c55fd1357091c9b0d099ad8c3a4bce7732b0c) work? 
I would test it myself if I could.

**Comment by RX14** [comment]
@lepakko683 why can't you test it?

**Comment by lepakko683** [comment]
@RX14 the buildscript doesn't work for me

**Comment by RX14** [comment]
Can you paste the gradle error?

**Comment by Lazersmoke** [comment]
@lepakko683 Try changing https://github.com/Vazkii/Botania/blob/master/build.properties#L4 to `dir_forgecraft=C\:/`. For some reason Vazkii put in a required directory that no one actually has ಠ_ಠ
It won't actually put any thing in your c drive. Make sure to `git rm build.properties` before commiting, though.

**Comment by lepakko683** [comment]
@Lazersmoke @RX14 I get this error: http://pastebin.com/K0MbWtvy

**Comment by RX14** [comment]
@lepakko683 ah I see you are using Linux. Simply touch private.properties, and set the dir_forgecraft to be /dev/null. This works on my arch machine.

Its a shame that Vazkii hates gradle and won't let anyone touch the build script, because it's really lacking.

**Pull request merged**
