### PR TITLE
The T in LGBT stands for Tater

### PR DESCRIPTION
**Pull request by SuicidalSteve**
-Add LGBTaters gotten by renaming tiny potato with certain names put between colons, originally based on the :pridetater: Discord emote.
Options are:
-Trans tater
-Nonbinary tater
-Gay tater
-Bi tater
-Pan tater
-Lesbian tater
-Genderfluid tater
-Asexual tater
-Aromantic tater

### CODE REVIEW

**Comment by SuicidalSteve** [comment]
oh god oh fuck

**Comment by williewillus** [comment]
why even have the colon support? seems strange

**Comment by SuicidalSteve** [comment]
ah, it was originally based on the three lgbtater emotes in vazcord, the only reason it has support for non-colons is cause Hubry said something about it

**Comment by SuicidalSteve** [comment]
anyhow, lemme just completely remove it then, might as well

**Pull request merged**
