### PR TITLE
Fixes a crash when an addon developer adds an empty ArrayList

### PR DESCRIPTION
**Pull request by Eladkay**

### CODE REVIEW

**Comment by JRoffel** [comment]
That commit name really cracked my up for some reason... I have to thank you for that :P

**Comment by Eladkay** [comment]
Uh why was this closed?

**Comment by JRoffel** [comment]
Probably because it is faster to just write this himself, than merge it... Or because Vazkii found a problem in the code you wrote...

**Comment by Eladkay** [comment]
Neither of these are possible.

**Comment by JRoffel** [comment]
So writing 4 lines of code can't be faster than a merge? Do you really think that?

**Comment by Eladkay** [comment]
Merging is literally pressing a button.

**Comment by JRoffel** [comment]
And will cost time to pull changes to local which, depending on the internet speed, will take a while (I think Vazkii has already stated that his internet isn't the fastest, though I can't be sure)

**Comment by Eladkay** [comment]
... that's all I have to say

**Comment by Lazersmoke** [comment]
@Eladkay probably the newline at line 68

**Comment by Eladkay** [comment]
In any case the issue isn't fixed. I'll try to push a new commit to fix formatting sometime.

**Pull request closed without merging**
