### PR TITLE
Descriptions update to en_US.lang

### PR DESCRIPTION
**Pull request by Spirit02**
Updated a bunch of wording / expressions / general flow of descriptions of roughly the first half of the document, at least by line number.

### CODE REVIEW

**Comment by Vazkii** [comment]
Have you tested if these fit in the book?

**Comment by Spirit02** [comment]
No. I suppose I'm going to have to learn to build from github and do some
testing?

**Comment by TheWhiteWolves** [comment]
Seeing as your only altering the lang file atm, you could just open a botania .jar with a zip program (winrar, 7zip etc) and replace the en_US.lang file in there and it should allow you to test out the change in your normal setup using the modified jar file.

**Comment by Spirit02** [comment]
I had just that thought. Good to hear it'll work, thank you.
I've still got about 800 lines to edit, then I'll start testing.

**Comment by Vazkii** [comment]
Closing for inactivity, feel free to open it again once you got it set up.

**Comment by Spirit02** [comment]
No worries. I've finished my initial run through. Got a few queries that
I'll shoot to you after I've done a bit of testing.

**Pull request closed without merging**
