### PR TITLE
Make baubles able to IBlockProvide

### PR DESCRIPTION
**Pull request by yrsegal**
This allows for things like the Botanical Addons toolbelt to provide from
the tools in them while worn.

HAS BEEN ACTUALLY TESTED THIS TIME :V

### CODE REVIEW

**Comment by TheWhiteWolves** [comment]
Question: Wouldn't it be more useful from a player perspective to to try pulling from the bauble inventory first rather than your personal inventory, i.e. say your pulling cobble, it would be more useful to leave a supply of cobble in your main inventory and take from the bauble inventory before depleting your on hand supply.

It's a simple thing but personally I would think it might be more beneficial this way.

**Comment by yrsegal** [comment]
True, true. That's a simple fix.

**Comment by yrsegal** [comment]
there you are.

**Comment by TheWhiteWolves** [comment]
Not to be picky but just want to point out you switched the count ones, so now the variable names are opposite to what they are counting :stuck_out_tongue_closed_eyes:

**Comment by yrsegal** [comment]
oops. also, easy to fix >.<

**Comment by yrsegal** [comment]
there :3

**Comment by TheWhiteWolves** [comment]
nice, also won't that also make it so the count doesn't include your inventory unless you have some in a bauble inventory.

Would this bit mean it will stop the count if your bauble has none, even when your inventory does? or would it return 0 for none found, I can't remember what the count returns.

```Java 
if (baubleCount == -1) return -1;
```

**Comment by yrsegal** [comment]
-1 means infinity in this case.

**Comment by TheWhiteWolves** [comment]
Yep, ignore me, forgot that's a method in that file, so once I expanded it and had a look it basically means your in creative mode

**Pull request merged**
