### PR TITLE
Removed @Nonnull descriptors as needed to not crash when viewing the …

### PR DESCRIPTION
**Pull request by Penrif**
…Botania creative tab and using the Lexicon

### CODE REVIEW

**Comment by williewillus** [comment]
what is this for? 

nullability annotations are not retained at runtime (unless your ide injects runtime checks, but that would cause crashes in forge itself before botania even runs)

**Comment by Penrif** [comment]
Just trying to get a functional dev environment.  Pulled down source, got it building, then would crash with stacks like the following:

java.lang.IllegalArgumentException: Argument for @Nonnull parameter 'bellows' of vazkii/botania/client/render/tile/RenderTileBellows.renderTileEntityAt must not be null
	at vazkii.botania.client.render.tile.RenderTileBellows.$$$reportNull$$$0(RenderTileBellows.java)
	at vazkii.botania.client.render.tile.RenderTileBellows.renderTileEntityAt(RenderTileBellows.java)
	at vazkii.botania.client.render.tile.RenderTileBellows.renderTileEntityAt(RenderTileBellows.java:24)
	at net.minecraftforge.client.ForgeHooksClient.renderTileItem(ForgeHooksClient.java:603)
...

So this is me fixing all the ones I hit by scanning through the Botania creative tab and using the Lexicon.  Spot checked a few deeper into the stack and in all the cases I found the null was an appropriate param for the situation.

**Comment by williewillus** [comment]
Disable runtime nonnull assertions in IntelliJ

**Comment by williewillus** [comment]
I'll pull it to fix the crashes in dev but generally those assertions are just annoying in modded :P

**Comment by Penrif** [comment]
Can do.  Curious tho, why mark up with 'em if they aren't enforced?

**Comment by Bluexin** [comment]
I find them useful as I write my mods in Kotlin (which is null-safe), so these annotation checks are useful as bridge ^-^

**Comment by williewillus** [comment]
Half of these aren't problems in 1.11 anymore, and I fixed the rest + other stuff in 1.11 as well, so closing this since it's not *super* critical

**Comment by Penrif** [comment]
Allright, I'll rebase my other branch that was off this...

**Pull request closed without merging**
