### PR TITLE
fix armor

### PR DESCRIPTION
**Pull request by MoriyaShiine**
you can ignore the launch profiles I accidentally pushed them lol

### CODE REVIEW

**Comment by williewillus** [comment]
remove the launch profiles

**Comment by williewillus** [comment]
also please describe the issue you're fixing

**Comment by MoriyaShiine** [comment]
it fixes this issue: https://github.com/Vazkii/Botania/issues/2882

Certain mods don't check for ISpecialArmor so when doing effects that check for armor, Botania armor is ignored. Ex in the monk mod, some effects only work if you're not wearing armor, but they work with Botania armor due to how it's implemented.

**Comment by williewillus** [comment]
you changed the whitespace of the entire file making it hard to see the real diff, revert those whitespace changes

**Pull request closed without merging**
