### PR TITLE
Re Translated ko_KR.lang file.

### PR DESCRIPTION
**Pull request by jomin398**
###I re translated ko_KR.lang file.

##Now,Everyone please watching below!!
https://github.com/jomin398/Botania/commit/a6c020b20a5962e06b051a72727d3d7457c9ea7c

### (Sorry this's first github)

I'm still playing 1.7.10 version of Botania:)

### CODE REVIEW

**Comment by Tamaized** [comment]
I.. uh.. ok

**Comment by JRoffel** [comment]
Uhm... what?

**Comment by Sunconure11** [comment]
What.

**Comment by jomin398** [comment]
Anyone know, how to direct upload edited file?
I'll try to re upload it.

**Pull request closed without merging**
