### PR TITLE
Add Livingwood and Dreamwood Fences and Fencegates

### PR DESCRIPTION
**Pull request by ToMe25**
This Pull Request adds Livingwood Fences and Fence Gates as well as Dreamwood Fences and Fence Gates.
This PR no longer removes Livingwood and Dreamwood walls even tho that materials are wood types and should have fences not walls.

### CODE REVIEW

**Comment by williewillus** [comment]
fine with adding fences and fence gates, but keep the walls

**Comment by ToMe25** [comment]
ok ill add them back.

**Comment by ToMe25** [comment]
First i had some problems with git, than i had something else i needed to do, but now i have finally readded the walls.

**Comment by ToMe25** [comment]
Could i get a reaction to the current state of this PR?
You said "fine with adding fences and fence gates", but that could mean alot of things including:
"I'm fine with that i will pull this" and
"I'm fine with that, but i need a response from someone else"...

Also whats about some of my other PR's (mainly #3087 and #3102 )?

**Pull request merged**
