### PR TITLE
Spelling, dying → dyeing

### PR DESCRIPTION
**Pull request by trejkaz**
Same as last time minus the two problematic spots.

### CODE REVIEW

**Comment by ruifung** [comment]
You should squash the commits.

**Comment by trejkaz** [comment]
I guess doing that is easy enough, but I figured it would cause problems because my existing commits are already public and the git docs say never to do that for stuff that's already visible to others.

**Comment by ruifung** [comment]
If nobody has pulled from your repository, you could just force push - or alternately make a new branch with the squashed commits for PR.

**Comment by trejkaz** [comment]
Aside from spooky automated pullbots, there wouldn't be anyone I hope.

Time to test the pullbots I guess. Well, time tonight anyway, right now I can't get to my computer.

**Comment by trejkaz** [comment]
Stuff caught fire, going to have to re-clone, manually apply, re-submit.

**Pull request closed without merging**
