### PR TITLE
Fixes many language issues, resolving #877 and #879, and including #887

### PR DESCRIPTION
**Pull request by Lazersmoke**
I flip flopped the flippy floops in the flippity flop!

### CODE REVIEW

**Comment by Lazersmoke** [comment]
These are the only languages that include the zodiac signs :)

**Comment by Chaotic-Potato** [comment]
*flops

**Comment by Chaotic-Potato** [comment]
This fixed 877 not 887 :P

**Comment by Vazkii** [comment]
This won't change the icons, I'll fix it later.

**Pull request closed without merging**
