### PR TITLE
Config for agricarnation white list

### PR DESCRIPTION
**Pull request by rqy2002**
Add config white list for agricarnation, to solve issues like "why agricarnations don't work on something" (such as #3815).

(although we can't judge which block is actually "a crop", players or modpack authors can control it by such a config)

### CODE REVIEW

**Comment by rqy2002** [comment]
(should we test isValidBonemealTarget then?)

**Comment by williewillus** [comment]
why not just a tag?

**Comment by rqy2002** [comment]
You are right. I'm just not familier to modding 😆

**Comment by TheRealWormbo** [comment]
Is this PR still being worked on?

**Pull request closed without merging**
