### PR TITLE
Readme logo fix :D

### PR DESCRIPTION
**Pull request by Lanrik**

### CODE REVIEW

**Comment by williewillus** [comment]
get rid of all the other pointless whitespace dedits

**Comment by Lanrik** [comment]
but this whitespace pointless

**Comment by williewillus** [comment]
Yes, so it isn't needed. Get rid of them

**Comment by Lanrik** [comment]
okay >_<

**Comment by yrsegal** [comment]
I'd suggest squashing the commits into one.

**Comment by Tamaized** [comment]
Aye, very bottom of https://github.com/Vazkii/Botania/blob/master/contributing.md
Vazkii would rather have PRs be one commit

**Comment by williewillus** [comment]
you can squash+pull now so not really necessary

**Pull request merged**
