### PR TITLE
fixed lang files for most entries

### PR DESCRIPTION
**Pull request by MelanX**
will fix other problems soon

### CODE REVIEW

**Comment by williewillus** [comment]
excellent, let me know when this is ready

**Comment by MelanX** [comment]
I fixed the missing stuff...
But I have a few questions: 
1. Do the slabFull entries be changed, too?
2. What's with the Vials? There is a mistake atm in the.. I don't know in English but I mean --> ( ) <-- this stuff :D 
3. Do you wanna remove the stuff which is not needed for yourself? Because I don't know what's not needed but a few things seems useless (because I didn't changed it)
4. Where is my money for the changes? Kappa (for real: Kappa) :)

**Comment by williewillus** [comment]
1. you can delete all the `slabFull` entries
2. fix the entry keys (left side), leave the values as they are for now, I will fix it later
3. I want to clean up stuff, but let's do that later after the port is complete.
4. you have our love and gratitude :P

**Comment by MelanX** [comment]
1. Done 😎 
4. That's nice, too :)

**Comment by MelanX** [comment]
Oh damn.. I wanted to translate a bit more into German and now I see a lot more stuff which I forgot because I only changed stuff which was missing in the english Minecraft.. update will follow soon :D 
sorry for a lot of (tiny) commits but I don't know how to delete commits which are already pushed :(

**Comment by williewillus** [comment]
no worries, I can squash when merging.

**Comment by MelanX** [comment]
Okay, I think I'm finally done with this PR :)

**Pull request merged**
