### PR TITLE
JEI Fixes

### LINKED ISSUE #2971: [1.14] Misc JEI integration issues remaining
- [ ] some pure daisy recipes error out when displaying
- [ ] runic altar mana bar goes out of bounds
- [ ] mana infusion doesn't show full pool

### PR DESCRIPTION
**Pull request by iTitus**
Fixes #2971 

- [x] some pure daisy recipes error out when displaying
    - inverted filtering: all non-empty input stacks in tags got discarded
    - wrong api usage: setInputLists vs setInputs
- [x] mana infusion doesn't show full pool
    - there was an error with the model jsons - not with JEI

~~runic altar mana bar goes out of bounds~~
sadly cannot reproduce

### CODE REVIEW

**Comment by iTitus** [comment]
I cannot reproduce the runic altar mana bar going out of bounds in the JEI view.
Any tips or reproduction steps for this?

**Comment by williewillus** [comment]
try with a small mc window

**Comment by iTitus** [comment]
Sorry I really cannot reproduce on my machine. I will leave this PR as is.

**Comment by MelanX** [comment]
maybe another gui scale?

**Pull request merged**
