### PR TITLE
Add uk_ua.json

### PR DESCRIPTION
**Pull request by mewnn**
Full Ukrainian localization of the mod, including the book :)

### CODE REVIEW

**Comment by TheRealWormbo** [comment]
I'm working on the German translation myself, so even though I don't know any Ukrainian and forgot everything about Russian (except the alphabet), I had a quick scroll though the file anyway for some general feedback. (Just sanity checking, no validation.)

There seem to be a couple of untranslated entries in the language file, which probably should not be there if they are not supposed to be different, as they get inherited from the English file: (as mentioned in the comments at the top of the file)
- botaniamisc.justDoIt
- botania.rank0..5
- botania.roman0..30
- block.botania.dandelifeon.reference
- block.botania.marimorphosis(_chibi).reference (Is this one based on an older version of the English language file?)
- item.botania.record_gaia_1.desc
- item.botania.record_gaia_2.desc
- botania.tagline.dreamwoodSpreader
- botania.page.agricarnation1
- botania.page.spectranthemum3
- botania.page.dandelifeon8
- botania.page.turntable1
- botania.page.brewery11b
- botania.page.manaBlaster3
- botania.page.slimeBottle1
- botania.page.blazeBlock1
- botania.page.preventingDecay0
- botania.subtitle.doit
- botania.subtitle.way

There are also some partially translated entries you might want to take another look at:
- botania.tagline.welcome – Doesn't transliterate "Botania" (although I think the tagline entries aren't even used anymore)
- botania.page.vineBall2 – "Vineacraft" is not transliterated, but that's probably fine.
- (botania.page.autocraftingHalo1 is fine, the Halo games have no official transliteration, as far as I can tell)
- botania.entry.bcIntegration – "Buildcraft" is not transliterated, but (1) I don't know if it has an official transliteration, and (2) I don't think that entire section is even in the Lexicon anymore.
- botania.subtitle.equipManasteel – "clanks" is not translated

I noticed some quoted strings within the Corporea Index pages that may need to be "untranslated", as they refer to typed search commands via chat. Keywords in those search queries (e.g. "all" or "stack") are not yet translatable, and the item names are matched by the server language. (Although there's a PR for the latter part.)

And finally, you might want to have another look at the various metamorphic stone types. They have been given more descriptive names (Fuchsite, Talc, etc.) recently. Some of those names are real minerals, others are made up.

**Comment by artemisSystem** [comment]
Hi @mewnn! Have you had a chance to look at these comments?

**Comment by mewnn** [comment]
> Hi @mewnn! Have you had a chance to look at these comments?

Hi, yes, I've seen it. Almost none of it is valid, so I just ignored it. I did this translation for me and my friends to play, it works great even in the latest versions :)

**Comment by TheRealWormbo** [comment]
Superseded by #4579. Feel free to submit further additions/corrections as a new PR.

**Pull request closed without merging**
